# app/encryption.py
from cryptography.fernet import Fernet

def generate_key():
    """
    Generates a new Fernet key for symmetric encryption.
    
    Fernet is a symmetric (secret-key) authenticated cryptography system that guarantees
    that a message encrypted using it cannot be manipulated or read without the key.
    
    Returns:
        bytes: A URL-safe, base64-encoded 32-byte key.
    """
    return Fernet.generate_key()

def encrypt_content(content: bytes, key: bytes) -> bytes:
    """
    Encrypts the given content using the provided Fernet key.

    Args:
        content (bytes): The raw data to be encrypted.
        key (bytes): The symmetric key generated by `generate_key()`.

    Returns:
        bytes: The encrypted ciphertext.
    """
    fernet = Fernet(key)
    return fernet.encrypt(content)

def decrypt_content(token: bytes, key: bytes) -> bytes:
    """
    Decrypts a Fernet token using the provided key.

    Args:
        token (bytes): The encrypted ciphertext to be decrypted.
        key (bytes): The symmetric key used for the original encryption.

    Returns:
        bytes: The original, decrypted data.
    """
    fernet = Fernet(key)
    return fernet.decrypt(token)