# app/simulation.py
import logging
import time
from pathlib import Path
from app.logger import EventLogger
from app.safety import ensure_in_sandbox, sandbox_root
from app.encryption import generate_key, encrypt_content

def setup_logging():
    """Configures the logging system to output to both a file and the console."""
    log_file = "output/logs.txt"
    Path(log_file).parent.mkdir(exist_ok=True)
    
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] - %(message)s",
        handlers=[
            logging.FileHandler(log_file),
            logging.StreamHandler()
        ]
    )

def malware_simulation():
    """
    Main function to run the sequence of simulated malware behaviors.
    
    This function orchestrates the entire simulation, from setup to executing
    each distinct malware action in a controlled and observable manner.
    """
    setup_logging()
    sandbox = sandbox_root()
    sandbox.mkdir(exist_ok=True) # Ensure the 'generated' directory exists
    
    logger = EventLogger()  # Initializes the structured JSONL logger

    logging.info("Malware simulation started.")
    logger.event("SIMULATION_START")

    # === 1. Key Generation ===
    # In a real-world ransomware attack, the encryption key would be generated by
    # the attacker and sent to a command-and-control (C2) server. The key would
    # likely never be stored on the victim's machine.
    # For this simulation, we save it in the sandbox so we can demonstrate decryption.
    key_path = ensure_in_sandbox(sandbox / "secret.key")
    if not key_path.exists():
        key = generate_key()
        key_path.write_bytes(key)
    else:
        key = key_path.read_bytes()
    logging.info(f"Encryption key generated and saved to {key_path}")
    logger.event("KEY_GENERATED", {"path": str(key_path)})
    time.sleep(0.5)

    # === 2. Persistence Simulation ===
    # This simulates a common malware technique to ensure it runs again after a reboot.
    # It copies a file to a "startup" folder. In a real scenario, this would be a
    # system directory like 'C:\\Users\\<User>\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup'.
    startup_dir = ensure_in_sandbox(sandbox / "startup_simulation")
    startup_dir.mkdir(exist_ok=True)
    persistence_file = ensure_in_sandbox(startup_dir / "malware_copy.py")
    persistence_file.write_text("# Simulated persistence mechanism")
    logging.info(f"Simulated persistence: Copied file to {persistence_file}")
    logger.event("PERSISTENCE_SIM", {"destination": str(persistence_file)})
    time.sleep(0.5)

    # === 3. Duplication/Replication Simulation ===
    # Malware often copies itself to multiple locations to increase its chances of
    # survival and execution. This simulates copying the malware to common user
    # directories like the Desktop and Documents folder.
    desktop_sim = ensure_in_sandbox(sandbox / "desktop_sim")
    documents_sim = ensure_in_sandbox(sandbox / "documents_sim")
    desktop_sim.mkdir(exist_ok=True)
    documents_sim.mkdir(exist_ok=True)
    
    dup_file_desktop = ensure_in_sandbox(desktop_sim / "duplicated_malware.py")
    dup_file_documents = ensure_in_sandbox(documents_sim / "duplicated_malware.py")
    
    dup_file_desktop.write_text("# Simulated duplicate")
    dup_file_documents.write_text("# Simulated duplicate")
    
    logging.info(f"Simulated duplication: Copied to {dup_file_desktop} and {dup_file_documents}")
    logger.event("DUPLICATION_SIM", {"locations": [str(dup_file_desktop), str(dup_file_documents)]})
    time.sleep(0.5)

    # === 4. File Analysis (Scanning) ===
    # Before encrypting, ransomware scans the filesystem to find valuable files
    # (e.g., documents, images, videos) while avoiding system files that could
    # crash the computer. This simulation targets a specific directory for simplicity.
    files_dir = Path.cwd() / "sandbox" / "text_files_to_encrypt"
    if not files_dir.exists():
        logging.warning(f"Directory not found: {files_dir}. Skipping file analysis and ransomware.")
    else:
        logging.info(f"Scanning for target files in '{files_dir}'...")
        for f in files_dir.iterdir():
            if f.is_file():
                logging.info(f"  - Found target: {f.name}")
                logger.event("FILE_SCANNED", {"path": str(f), "size": f.stat().st_size})
        time.sleep(0.5)

        # === 5. Ransomware Simulation (Encryption) ===
        # This is the core of the ransomware behavior. It iterates through the
        # identified target files, encrypts their content, and replaces the
        # original file with the encrypted version.
        logging.info("Initiating ransomware simulation (encryption)...")
        for f in files_dir.iterdir():
            if f.is_file() and f.suffix == ".txt":
                try:
                    # Read original content
                    original_content = f.read_bytes()
                    
                    # Encrypt content using the generated key
                    encrypted_content = encrypt_content(original_content, key)
                    
                    # Define the new encrypted file name and path
                    encrypted_file = f.with_suffix(".txt.encrypted_sim")
                    encrypted_file.write_bytes(encrypted_content)
                    
                    # In a real attack, the original file is securely deleted.
                    # Here, we just remove it.
                    f.unlink() 
                    
                    logging.info(f"  - Encrypted '{f.name}' -> '{encrypted_file.name}'")
                    logger.event("RANSOMWARE_SIM", {"original": str(f), "encrypted_file": str(encrypted_file)})
                except Exception as e:
                    logging.error(f"Failed to encrypt {f.name}: {e}")
        time.sleep(0.5)

    # === 6. Propagation Simulation ===
    # This simulates a worm-like behavior where malware attempts to spread across
    # a network. In this simplified version, it just creates copies in a
    # "propagation" directory, simulating discovery of and infection of other
    # network shares or devices.
    prop_dir = ensure_in_sandbox(sandbox / "propagation_sim")
    prop_dir.mkdir(exist_ok=True)
    for i in range(2):
        prop_file = ensure_in_sandbox(prop_dir / f"propagated_copy_{i}.py")
        prop_file.write_text("# Simulated propagation to another host")
        logging.info(f"Simulated propagation: Created {prop_file}")
        logger.event("PROPAGATION_SIM", {"destination": str(prop_file)})
    time.sleep(0.5)

    logging.info("Malware simulation finished.")
    logger.event("SIMULATION_END")